[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vidore_benchmark"
version = "0.0.1"
description = "Visual Document Retrieval: Benchmark"
authors = [
    { name = "Manuel Faysse", email = "manuel.faysse@illuin.tech" },
    { name = "Hugues Sibille", email = "hugues.sibille@illuin.tech" },
    { name = "Tony Wu", email = "tony.wu@illuin.tech" },
]
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

dependencies = [
    "datasets>=2.15.0",
    "einops>=0.8.0",
    "mteb>=1.12.47",
    "peft>=0.11.1",
    "python-dotenv>=1.0.1",
    "torch>=2.0.0",
    "transformers>=4.41.1",
    "typer>=0.12.3",
]

[project.optional-dependencies]
dev = [
    "black>=24.4.2",
    "coverage>=7.5.2",
    "ipykernel>=6.29.4",
    "mypy>=1.10.0",
    "pytest>=8.2.1",
    "ruff>=0.4.5",
]
baselines = [
    "accelerate==0.30.1",
    "configue==5.0.0",
    "datasets==2.19.1",
    "diskcache==5.6.3",
    "einops==0.8.0",
    "FlagEmbedding==1.2.10",
    "matplotlib==3.9.0",
    "mteb==1.12.47",
    "pdf2image==1.17.0",
    "pytesseract==0.3.10",
    "rank-bm25==0.2.2",
    "scikit-learn==1.5.0",
    "seaborn==0.13.2",
    "sentencepiece==0.2.0",
    "sentence-transformers==3.0.1",
    "torch==2.2.2",
    "transformers==4.41.1",
]

demo = [
    "gradio"
]

[project.urls]
homepage = "https://github.com/tonywu71/vidore-benchmark"

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120
